#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# VANTAGE-STR — Global Multi-Node Deployment Script
# Phase 6: Spins up 5 simulated forensic DNA nodes across continents
# ═══════════════════════════════════════════════════════════════════════════════
#
# Each node:
#   1. Initializes a local Milvus vector DB with synthetic STR profiles
#   2. Registers with the Global Orchestrator via mTLS
#   3. Starts its local DSPy Forensic Agent and ZKP Prover
#
# Usage:
#   chmod +x infra/deploy_global.sh
#   ./infra/deploy_global.sh [up|down|status]
#
# Prerequisites:
#   - Docker & Docker Compose v2
#   - OpenSSL (for mTLS certificate generation)
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────

PROJECT_NAME="vantage-str"
NETWORK_NAME="${PROJECT_NAME}-global"
ORCHESTRATOR_PORT=8000

declare -A NODES=(
    ["jandarma-tr"]="Turkey|Istanbul|TR|8101|100"
    ["bka-de"]="Germany|Frankfurt|DE|8102|150"
    ["npa-jp"]="Japan|Tokyo|JP|8103|80"
    ["fbi-us"]="USA|Washington|US|8104|200"
    ["pf-br"]="Brazil|Brasilia|BR|8105|120"
)

CERTS_DIR="./infra/certs"
DATA_DIR="./infra/data"
COMPOSE_FILE="./infra/docker-compose.global.yml"

# ── Colors ────────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color
BOLD='\033[1m'

log()   { echo -e "${CYAN}[VANTAGE]${NC} $1"; }
ok()    { echo -e "${GREEN}[  OK  ]${NC} $1"; }
warn()  { echo -e "${YELLOW}[ WARN ]${NC} $1"; }
err()   { echo -e "${RED}[ERROR ]${NC} $1"; }

# ── Certificate Generation ────────────────────────────────────────────────────

generate_mtls_certs() {
    log "Generating mTLS certificates..."
    mkdir -p "${CERTS_DIR}"

    # Root CA
    if [ ! -f "${CERTS_DIR}/ca.key" ]; then
        openssl genrsa -out "${CERTS_DIR}/ca.key" 4096 2>/dev/null
        openssl req -new -x509 -days 365 -key "${CERTS_DIR}/ca.key" \
            -out "${CERTS_DIR}/ca.crt" \
            -subj "/CN=VANTAGE-STR Root CA/O=Forensic Network/C=INT" 2>/dev/null
        ok "Root CA generated"
    else
        ok "Root CA already exists"
    fi

    # Orchestrator cert
    if [ ! -f "${CERTS_DIR}/orchestrator.key" ]; then
        openssl genrsa -out "${CERTS_DIR}/orchestrator.key" 2048 2>/dev/null
        openssl req -new -key "${CERTS_DIR}/orchestrator.key" \
            -out "${CERTS_DIR}/orchestrator.csr" \
            -subj "/CN=orchestrator/O=VANTAGE-STR/C=INT" 2>/dev/null
        openssl x509 -req -in "${CERTS_DIR}/orchestrator.csr" \
            -CA "${CERTS_DIR}/ca.crt" -CAkey "${CERTS_DIR}/ca.key" \
            -CAcreateserial -out "${CERTS_DIR}/orchestrator.crt" -days 365 2>/dev/null
        rm -f "${CERTS_DIR}/orchestrator.csr"
        ok "Orchestrator certificate generated"
    fi

    # Node certs
    for node_id in "${!NODES[@]}"; do
        if [ ! -f "${CERTS_DIR}/${node_id}.key" ]; then
            IFS='|' read -r country city code port profiles <<< "${NODES[$node_id]}"
            openssl genrsa -out "${CERTS_DIR}/${node_id}.key" 2048 2>/dev/null
            openssl req -new -key "${CERTS_DIR}/${node_id}.key" \
                -out "${CERTS_DIR}/${node_id}.csr" \
                -subj "/CN=${node_id}/O=VANTAGE-STR/C=${code}" 2>/dev/null
            openssl x509 -req -in "${CERTS_DIR}/${node_id}.csr" \
                -CA "${CERTS_DIR}/ca.crt" -CAkey "${CERTS_DIR}/ca.key" \
                -CAcreateserial -out "${CERTS_DIR}/${node_id}.crt" -days 365 2>/dev/null
            rm -f "${CERTS_DIR}/${node_id}.csr"
            ok "Certificate for ${node_id} (${country})"
        fi
    done
}

# ── Docker Compose Generation ─────────────────────────────────────────────────

generate_compose() {
    log "Generating Docker Compose configuration..."
    mkdir -p "$(dirname "${COMPOSE_FILE}")"

    cat > "${COMPOSE_FILE}" << 'HEADER'
# ═══════════════════════════════════════════════════════════════════════════════
# VANTAGE-STR — Global Network Docker Compose
# Auto-generated by deploy_global.sh
# ═══════════════════════════════════════════════════════════════════════════════

version: "3.9"

networks:
  vantage-global:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  # ── Global Orchestrator ──
  orchestrator:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: vantage-orchestrator
    ports:
      - "8000:8000"
    environment:
      - VANTAGE_ROLE=orchestrator
      - VANTAGE_MTLS_CA=/certs/ca.crt
      - VANTAGE_MTLS_CERT=/certs/orchestrator.crt
      - VANTAGE_MTLS_KEY=/certs/orchestrator.key
    volumes:
      - ../infra/certs:/certs:ro
    networks:
      vantage-global:
        ipv4_address: 172.28.0.2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

HEADER

    # Generate node services
    local ip_suffix=10
    for node_id in $(echo "${!NODES[@]}" | tr ' ' '\n' | sort); do
        IFS='|' read -r country city code port profiles <<< "${NODES[$node_id]}"

        cat >> "${COMPOSE_FILE}" << NODEBLOCK
  # ── Node: ${node_id} (${country}, ${city}) ──
  ${node_id}:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: vantage-${node_id}
    ports:
      - "${port}:8000"
    environment:
      - VANTAGE_ROLE=node
      - VANTAGE_NODE_ID=${node_id}
      - VANTAGE_COUNTRY=${code}
      - VANTAGE_CITY=${city}
      - VANTAGE_ORCHESTRATOR_URL=http://172.28.0.2:8000
      - VANTAGE_SYNTHETIC_PROFILES=${profiles}
      - VANTAGE_MTLS_CA=/certs/ca.crt
      - VANTAGE_MTLS_CERT=/certs/${node_id}.crt
      - VANTAGE_MTLS_KEY=/certs/${node_id}.key
      - VANTAGE_ZKP_ENABLED=true
      - VANTAGE_DSPY_ENABLED=true
    volumes:
      - ../infra/certs:/certs:ro
    depends_on:
      orchestrator:
        condition: service_healthy
    networks:
      vantage-global:
        ipv4_address: 172.28.0.${ip_suffix}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

NODEBLOCK
        ((ip_suffix++))
    done

    ok "Docker Compose file generated at ${COMPOSE_FILE}"
}

# ── Commands ──────────────────────────────────────────────────────────────────

cmd_up() {
    echo ""
    echo -e "${BOLD}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}  VANTAGE-STR — Global Network Deployment${NC}"
    echo -e "${BOLD}═══════════════════════════════════════════════════════════${NC}"
    echo ""

    generate_mtls_certs
    generate_compose

    log "Launching global network (${#NODES[@]} nodes + orchestrator)..."
    echo ""

    for node_id in $(echo "${!NODES[@]}" | tr ' ' '\n' | sort); do
        IFS='|' read -r country city code port profiles <<< "${NODES[$node_id]}"
        echo -e "  ${GREEN}●${NC} ${BOLD}${node_id}${NC} — ${country}, ${city} (${profiles} profiles) → :${port}"
    done

    echo ""
    docker compose -f "${COMPOSE_FILE}" -p "${PROJECT_NAME}" up -d --build

    echo ""
    ok "Global network is live!"
    echo -e "  ${CYAN}Orchestrator:${NC} http://localhost:${ORCHESTRATOR_PORT}"
    for node_id in $(echo "${!NODES[@]}" | tr ' ' '\n' | sort); do
        IFS='|' read -r _ _ _ port _ <<< "${NODES[$node_id]}"
        echo -e "  ${CYAN}${node_id}:${NC} http://localhost:${port}"
    done
    echo ""
}

cmd_down() {
    log "Shutting down global network..."
    docker compose -f "${COMPOSE_FILE}" -p "${PROJECT_NAME}" down -v
    ok "Global network stopped."
}

cmd_status() {
    log "Network status:"
    docker compose -f "${COMPOSE_FILE}" -p "${PROJECT_NAME}" ps
}

# ── Entry Point ───────────────────────────────────────────────────────────────

case "${1:-up}" in
    up)     cmd_up ;;
    down)   cmd_down ;;
    status) cmd_status ;;
    *)
        echo "Usage: $0 [up|down|status]"
        exit 1
        ;;
esac
